default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV["RAILS_DB_POOL"] || ENV['RAILS_MAX_THREADS'] || 5 %>
  idle_timeout: <%= ENV["RAILS_IDLE_CONNECTION"] ||  60 %>
  port: <%= ENV['RAILS_DATABASE_PORT'] || 5432 %>
  host: localhost
  username: postgres
  password: postgres
  port: 5432

development:
  <<: *default
  database: insta-develop_development

test:
  <<: *default
  database: insta-develop_test

production:
  <<: *default
  database: insta-develop_production

